name: Deploy website to Hostinger

on:
  push:
    branches:
      - main  # The branch name you are committing the new changes to

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Deploy to Hostinger
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: List root directory contents
        run: ls -al
      
      - name: List subdirectories
        run: find . -maxdepth 2 -type d
      
      - name: Push to Hostinger
        uses: s0/git-publish-subdir-action@develop
        with:
          source-directory: .  # Deploy the contents of the root folder
        env:
          REPO: https://github.com/macca1b/web1.git
          BRANCH: main  # Deploy to main branch on Hostinger
          FOLDER: .  # Deploy the contents of the root folder
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"
